version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    restart: always

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vision_forge
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres

volumes:
  redis-data:
  postgres-data:
